### ISSUE TITLE
readme.md missing...

### ISSUE THREAD

**Issue by Grimeton** [PetterKraabol/Twitch-Python#1]
$ pip install twitch-python
Collecting twitch-python
  Using cached https://files.pythonhosted.org/packages/66/04/9849cd2be54bcc27953691b98235429af2d84e4f89a865fca4a34d7eba6a/twitch-python-0.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Cygwin64\tmp\pip-install-7vhnlb2o\twitch-python\setup.py", line 5, in <module>
        with open('readme.md') as readme_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Cygwin64\tmp\pip-install-7vhnlb2o\twitch-python\

**Comment by PetterKraabol** [comment]
Thanks!
Added missing manifest.in file in 347708ef71b4e7653806be02849039a47fc8307a to fix this.
