### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CodeSpent** [PetterKraabol/Twitch-Python#11]
Opening issue for improving on current documentation as the few examples are lacking of documenting the rest of the library. I'm happy to help contribute this.

I will continue to update this issue with progress and roadmap as I work through this.

**Comment by PetterKraabol** [comment]
Hi, there are some additional examples in the [wiki](https://github.com/PetterKraabol/Twitch-Python/wiki), however, hand-written documentation is prone to be outdated.

Modern editors (I use intelliJ) will give you hints that should be enough to explore the library. I use [type hints](https://docs.python.org/3/library/typing.html) in my Python code to tag variable types, which should also be picked up by most editors.

<img width="345" alt="Screenshot 2020-01-14 at 21 54 10" src="https://user-images.githubusercontent.com/2125142/72381859-69ae6100-3718-11ea-82e7-30e565c1f7fe.png">
<img width="829" alt="Screenshot 2020-01-14 at 21 56 28" src="https://user-images.githubusercontent.com/2125142/72382032-b8f49180-3718-11ea-97e8-feff8de5632c.png">

Most API functions take `**kwargs`, which are forwarded to api requests to provide optional parameters defined in the [Twitch API Reference](https://dev.twitch.tv/docs/api/reference).
As such, you can

```python
for video in helix.user('username').videos(first=10, type='highlight'):
    print(video.title)
```
