### ISSUE TITLE
Remove pipenv usage in setup.py

### ISSUE THREAD

**Issue by jonringer** [PetterKraabol/Twitch-Python#13]
Referencing pipenv from setup.py is unusual. A package shouldn't know about a environment tool. 

For packaging this in sandboxed environments, the usage needs to be removed https://github.com/NixOS/nixpkgs/blob/bb78090abff9968fbb8699b7422078d2ff040ce1/pkgs/development/python-modules/twitch-python/setup-no-pipenv.patch

**Comment by PetterKraabol** [comment]
Thank you, I've removed this dependency in 0.0.18
