### ISSUE TITLE
OAuth now required for all endpoints

### ISSUE THREAD

**Issue by Sevadus** [PetterKraabol/Twitch-Python#18]
As per https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916 all calls now require oauth.  Can we get oauth support updated just like in twitch-chat-downloader?

**Comment by AgenticJamesBond** [comment]
Hmm, dang...

**Comment by PetterKraabol** [comment]
Fixed in 0.0.19
https://pypi.org/project/twitch-python/0.0.19/

`pip install twitch-python --upgrade`
