### ISSUE TITLE
Namespace conflict with python-twitch-client

### ISSUE THREAD

**Issue by underchemist** [PetterKraabol/Twitch-Python#2]
Thanks for the great package. I'm trying to use both your package and python-twitch-client but both packages are imported like

```import twitch```
 
So naturally there is a namespace conflict. Would it be possible in the future to move away from a common package name and something a bit more specific? 

The other option I have is to rename the package myself after pip install but it's a little messy as i'm not sure where all the references to the package name exist in the package code itself.

**Comment by PetterKraabol** [comment]
Ideally, Twitch-Python should support all of Twitch's API so you don't have to use other (similar) packages. Create and issue (or PR) for any missing API endpoints you need and I'll look into it.

**Comment by underchemist** [comment]
Yeah that's fair. It feels a little redundant but I'll open a new issue for the specific functionality that I'm missing. If I get around to it I'll submit the PR but just to have it documented is maybe useful for you as well.
