### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by underchemist** [PetterKraabol/Twitch-Python#4]
Hi again,

from what I can tell you set some rate limiting parameter but it's not clear to me if it's actually used? is that accurate? or am I missing where it's actually limiting the requests by rate limit?

Cheers

**Comment by PetterKraabol** [comment]
That's correct, rate-limiting is not implemented at the moment.

I'll look into it.

**Comment by underchemist** [comment]
from a quick look at the code, it would seem that rate limiting has been implemented. Should this be closed?

**Comment by PetterKraabol** [comment]
I can close this for now, but the implementation is not optimal.

Twitch's API uses a point system and returns
- `Ratelimit-Limit`: total amount of points
- `Ratelimit-Remaining`: points remaining
- `Ratelimit-Reset`: time when remaining points == total points

Sleeping for the next available point requires keeping track of when the last *N* request were made, where *N* is the Ratelimit-Limit. Currently, it will sleep for either 10 seconds or *time.now() - Ratelimit-Reset*, whichever is lowest.
